{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-sb
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "configs-sb/*.*").AsConfig | nindent 2 }}
{{- end }}