{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: standbydb-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "readreplica.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 5432
      
  selector:
    {{- include "readreplica.selectorLabels" . | nindent 4 }}
{{- end }}