# Default values for python-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

primarydb:
  enabled: true
  service:
    type: NodePort
    port: 5432
  replicaCount: 1

  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "10"
  persistentVolume:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    volumeName: primarydb
    storageClass: hostpath
    mountPath: /run/desktop/mnt/host/c/users/ardab/primarydb
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
      

readreplica:
  enabled: true
  service:
    type: NodePort
    port: 5432
  replicaCount: 1

  image:
    repository: postgres
    pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
    tag: "10"
  persistentVolume: 
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    volumeName: standbydb
    storageClass: hostpath
    mountPath: /run/desktop/mnt/host/c/users/ardab/standbydb
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

pythonapp:
  enabled: true
  service:
    type: LoadBalancer
    port: 4455
  replicaCount: 1

  image:
    repository: ardabaran/pythonwebapp
    pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  smtpUser: admin@domain.com
  smtpPass: example
  smtpServer: smtp.domain.com
  smtpPort: 25
  smtpUseTls: false
  smtpUseSsl: false

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

global:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  dbPassword: example
  dbUser: admin
  dbName: python-app
  
  ingress:
    enabled: true
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      host: application.domain.com
      path: /
      pathType: ImplementationSpecific
    tls: []



