{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: python-app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ default "" .Values.global.dbPassword | b64enc | quote }}
  MAIL_PASSWORD: {{ default "" .Values.global.smtpPass | b64enc | quote }}
{{- end }}